spring:
  application:
    name: kilimanjaro
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

auth:
  grpc:
    host: localhost
    port: 9090
    secure: false

public:
  routes:
    - ^/api/v1/public($|/.*)
    - ^/health$